<?php
echo "<script src=\"reze_frame_w/jquery-3.6.1.min.js\"></script>";
include "universal.html";
include "fxn.php";
include "navbar.php";
include "navbar2.php";
include "hardcard.php";
include "softcard.php";
include "card_container.php";
include "section3.php";
include "section4.php";
include "home.php";
include "image_section_content.php";
include "content_section_image.php";
include "image_long_block.php";
include "long_block_image.php";
include "block_image_block.php";
include "review.php";
include "footer.php";
include "reversed_home.php";
include "home2.php";
include "experience.php";
include "login.php";
include "a_login.php";
include "slant_home.php";
include "circleimage.php";
include "slant_block.php";
include "mcurve_block.php";
include "bcurve_block.php";
include "contact_us.php";
include "video_home.php";
?>
